[build]
  publish = "."
  functions = "netlify/functions"

[[redirects]]
  from = "/voxpro-manager"
  to = "/templates/voxpro-manager.html"
  status = 200
  force = true

[[redirects]]
  from = "/assets/*"
  to = "/assets/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
