# Improved Netlify Configuration for VoxPro
# Based on the working Audio Memory Game setup

[build]
  publish = "."
  functions = "netlify/functions"

# API routing - ensures all API calls go to functions
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

# Specific function routing for diagnostics
[[redirects]]
  from = "/test-xano"
  to = "/.netlify/functions/xano-diagnostic-test"
  status = 200

[[redirects]]
  from = "/test-data"
  to = "/.netlify/functions/xano-data-fetch"
  status = 200

# Media proxy routing
[[redirects]]
  from = "/media-proxy/*"
  to = "/.netlify/functions/improved-fetch-media?url=:splat"
  status = 200

# Fallback for SPA routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Headers for CORS and security
[[headers]]
  for = "/api/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Headers = "Content-Type, Authorization"
    Access-Control-Allow-Methods = "GET, POST, PUT, DELETE, OPTIONS"

[[headers]]
  for = "/.netlify/functions/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Headers = "Content-Type, Authorization"
    Access-Control-Allow-Methods = "GET, POST, PUT, DELETE, OPTIONS"

# Environment variables (set these in Netlify dashboard)
# XANO_API_BASE = "https://xajo-bs7d-cagt.n7e.xano.io/api:pYeQctVX"
# XANO_API_KEY = "your-api-key-if-needed"

# Function configuration
[functions]
  directory = "netlify/functions"
  
  # Increase timeout for media operations
  [functions."improved-fetch-media"]
    timeout = 30
    
  [functions."xano-data-fetch"]
    timeout = 15
    
  [functions."xano-diagnostic-test"]
    timeout = 20

