# Improved Netlify Configuration for VoxPro
# Based on the working Audio Memory Game setup

[build]
  publish = "."
  functions = "netlify/functions"

# API routing - ensures all API calls go to functions
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

# Specific function routing for diagnostics
[[redirects]]
  from = "/test-xano"
  to = "/.netlify/functions/xano-diagnostic-test"
  status = 200

[[redirects]]
  from = "/test-data"
  to = "/.netlify/functions/xano-data-fetch"
  status = 200

# Media proxy routing
[[redirects]]
  from = "/media-proxy/*"
  to = "/.netlify/functions/fetch-media?url=:splat"
  status = 200

# File Manager routing
[[redirects]]
  from = "/file-manager"
  to = "/.netlify/functions/file-manager-page"
  status = 200

# VoxPro Manager routing (SPECIFIC - not catch-all)
[[redirects]]
  from = "/voxpro-manager"
  to = "/index.html"
  status = 200

# Root redirect to VoxPro Manager
[[redirects]]
  from = "/"
  to = "/voxpro-manager"
  status = 302

# Headers for CORS and security
[[headers]]
  for = "/api/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Headers = "Content-Type, Authorization"
    Access-Control-Allow-Methods = "GET, POST, PUT, DELETE, OPTIONS"

[[headers]]
  for = "/.netlify/functions/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Headers = "Content-Type, Authorization"
    Access-Control-Allow-Methods = "GET, POST, PUT, DELETE, OPTIONS"

# Function configuration
[functions]
  directory = "netlify/functions"

[functions."fetch-media"]
  timeout = 30

[functions."xano-data-fetch"]
  timeout = 15

[functions."xano-diagnostic-test"]
  timeout = 20
