# This section controls the build settings for your site.
[build]
  # Publish the main directory
  publish = "."

  # This gives Netlify a safe, empty command to run so it doesn't fail.
  command = "echo 'No build command required'"

# This section tells Netlify where to find your serverless functions.
[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"

# Configure headers for better security and caching
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    Cache-Control = "public, max-age=300"

# Specific headers for media files
[[headers]]
  for = "*.mp3"
  [headers.values]
    Cache-Control = "public, max-age=604800"
    Access-Control-Allow-Origin = "*"

[[headers]]
  for = "*.mp4"
  [headers.values]
    Cache-Control = "public, max-age=604800"
    Access-Control-Allow-Origin = "*"

# Headers for the voxpro-manager
[[headers]]
  for = "/voxpro-manager"
  [headers.values]
    Cache-Control = "no-store"
    X-Content-Type-Options = "nosniff"
    Content-Security-Policy = "default-src 'self' https: blob: data:; img-src * data: blob:; media-src * data: blob:; connect-src *; script-src 'self' https://cdnjs.cloudflare.com; style-src 'self' 'unsafe-inline'; frame-src *;"
