[[redirects]]
  from = "/file-manager"
  to = "/.netlify/functions/file-manager-page"
  status = 200

[[redirects]]
  from = "/voxpro-manager"
  to = "/templates/voxpro-manager.html"
  status = 200

# Catch-all MUST be last
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
