[build]
  functions = "netlify/functions"

# Function CORS is handled in code; these headers are fine to keep simple.
[[headers]]
  for = "/.netlify/functions/*"
  [headers.values]
    Access-Control-Allow-Methods = "GET, OPTIONS"
    Access-Control-Allow-Headers = "Content-Type, Authorization"
