[build]
  publish   = "."
  functions = "netlify/functions"

[[redirects]]
  from = "/file-manager"
  to   = "/.netlify/functions/uploader"
  status = 200
  force  = true

# Keep this LAST
[[redirects]]
  from = "/*"
  to   = "/index.html"
  status = 200
