[build]
  functions = "netlify/functions"

[build.environment]
  NODE_VERSION = "18"
  PYTHON_VERSION = "3.9"

[[headers]]
  for = "/netlify/functions/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Headers = "Content-Type, Authorization"
    Access-Control-Allow-Methods = "GET, POST, PATCH, DELETE, OPTIONS"

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/server"
  status = 200
