[build]
  functions = "netlify/functions"

[build.environment]
  NODE_VERSION = "18"

[[headers]]
  for = "/netlify/functions/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Headers = "Content-Type, Authorization"
    Access-Control-Allow-Methods = "GET, POST, PATCH, DELETE, OPTIONS"

[[redirects]]
  from = "/voxpro-manager"
  to = "/voxpro-manager.html"
  status = 200

[[redirects]]
  from = "/voxpro-manager/"
  to = "/voxpro-manager.html"
  status = 200
