[build]
  functions = "netlify/functions"

[[headers]]
  for = "/.netlify/functions/*"
  [headers.values]
    Access-Control-Allow-Methods = "GET,POST,PATCH,PUT,DELETE,OPTIONS"
    Access-Control-Allow-Headers = "Content-Type, Authorization"
