[build]
  publish   = "."
  functions = "netlify/functions"

# Pretty URL for the uploader
[[redirects]]
  from = "/file-manager"
  to   = "/.netlify/functions/file-manager-upload"
  status = 200
  force  = true

# Keep this LAST
[[redirects]]
  from = "/*"
  to   = "/index.html"
  status = 200
