[build]
  publish   = "."
  functions = "netlify/functions"

# Pretty route -> render the form (function page)
[[redirects]]
  from = "/file-manager"
  to   = "/.netlify/functions/file-manager-page"
  status = 200
  force  = true

# (Optional) legacy pretty POST path -> upload function
[[redirects]]
  from = "/file-manager-upload"
  to   = "/.netlify/functions/file-manager-upload"
  status = 200

# KEEP THIS LAST
[[redirects]]
  from = "/*"
  to   = "/index.html"
  status = 200
