# ---------- Build ----------
[build]
  publish   = "."
  functions = "netlify/functions"
  command   = "echo 'No build command needed'"

[functions]
  node_bundler = "esbuild"

# ---------- Routes ----------
# VoxPro Manager (static HTML)
[[redirects]]
  from   = "/voxpro-manager"
  to     = "/templates/voxpro-manager.html"
  status = 200

# Upload form (function-rendered page)
[[redirects]]
  from   = "/file-manager"
  to     = "/.netlify/functions/file-manager-page"
  status = 200

# Upload API (function)
[[redirects]]
  from   = "/file-manager-upload"
  to     = "/.netlify/functions/file-manager-upload"
  status = 200

# Optional /api/* proxy to functions
[[redirects]]
  from   = "/api/*"
  to     = "/.netlify/functions/:splat"
  status = 200

# Root → VoxPro Manager
[[redirects]]
  from   = "/"
  to     = "/voxpro-manager"
  status = 302
