# Enhanced netlify.toml for VoxPro Manager
# This configuration includes proper CSP settings and function configuration

[build]
  # Publish the main directory
  publish = "."

  # This gives Netlify a safe, empty command to run so it doesn't fail.
  command = "echo 'No build command required'"
  
  # Function directory
  functions = "netlify/functions"

# Configure headers for better security and caching
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = "camera=(), microphone=(), geolocation=()"
    Cache-Control = "public, max-age=300"
    # Enhanced CSP that allows media loading and inline scripts
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline' https://cdn.jsdelivr.net https://cdnjs.cloudflare.com; style-src 'self' 'unsafe-inline' https://cdn.jsdelivr.net https://cdnjs.cloudflare.com https://fonts.googleapis.com; img-src 'self' data: blob: https:; media-src 'self' data: blob: https:; connect-src 'self' https://*.netlify.app https://*.netlify.com https://*.xano.io https:; font-src 'self' https://cdnjs.cloudflare.com https://fonts.gstatic.com; frame-src 'self'"

# Specific headers for media files
[[headers]]
  for = "*.mp3"
  [headers.values]
    Content-Type = "audio/mpeg"
    Accept-Ranges = "bytes"
    Cache-Control = "public, max-age=604800"
    Access-Control-Allow-Origin = "*"

[[headers]]
  for = "*.mp4"
  [headers.values]
    Content-Type = "video/mp4"
    Accept-Ranges = "bytes"
    Cache-Control = "public, max-age=604800"
    Access-Control-Allow-Origin = "*"

[[headers]]
  for = "*.jpg"
  [headers.values]
    Content-Type = "image/jpeg"
    Cache-Control = "public, max-age=604800"
    Access-Control-Allow-Origin = "*"

[[headers]]
  for = "*.png"
  [headers.values]
    Content-Type = "image/png"
    Cache-Control = "public, max-age=604800"
    Access-Control-Allow-Origin = "*"

# Headers for the voxpro-manager
[[headers]]
  for = "/voxpro-manager"
  [headers.values]
    Cache-Control = "no-store"
    X-Content-Type-Options = "nosniff"

# Redirect configuration
[[redirects]]
  from = "/"
  to = "/voxpro-manager"
  status = 302

[[redirects]]
  from = "/voxpro-manager"
  to = "/voxpro-manager.html"
  status = 200

# Function settings
[functions]
  node_bundler = "esbuild"
  included_files = ["assets/**", "templates/**"]
  external_node_modules = ["node-fetch"]

# Environment variable setup
[build.environment]
  NODE_VERSION = "16"
