# Netlify configuration for VoxPro Manager
[build]
  publish = "public"
  functions = "netlify/functions"

# Function-specific configuration
[functions]
  node_bundler = "esbuild"
  
  [functions.cloudinary-metadata]
    timeout = 300
    memory = 1024
    runtime = "nodejs18.x"

# Headers for CORS support
[[headers]]
  for = "/api/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Headers = "Content-Type, Authorization"
    Access-Control-Allow-Methods = "GET, POST, PUT, DELETE, OPTIONS"

# Security headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline' 'unsafe-eval' https://widget.cloudinary.com https://upload-widget.cloudinary.com; style-src 'self' 'unsafe-inline'; img-src 'self' data: https: https://res.cloudinary.com; connect-src 'self' https://api.cloudinary.com https://res.cloudinary.com;"

# Redirects for API endpoints
[[redirects]]
  from = "/api/upload"
  to = "/.netlify/functions/uploader-fixed"
  status = 200

# Build plugins (optional - for optimization)
[[plugins]]
  package = "@netlify/plugin-functions-install-core"
