# Updated Netlify Configuration for VoxPro

[build]
  publish = "."
  functions = "netlify/functions"
  command = "echo 'No build command needed'"

# Define function-specific settings
[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"
  
# Explicitly include the file-manager-upload function
[functions."file-manager-upload"]
  included_files = ["netlify/functions/file-manager-upload.js"]

# API routing - ensures all API calls go to functions
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

# File Manager routing
[[redirects]]
  from = "/file-manager"
  to = "/.netlify/functions/file-manager-page"
  status = 200

# Explicit redirect for file-manager-upload
[[redirects]]
  from = "/file-manager-upload"
  to = "/.netlify/functions/file-manager-upload"
  status = 200

# Make sure Netlify functions are properly accessible
[[redirects]]
  from = "/.netlify/functions/*"
  to = "/.netlify/functions/:splat"
  status = 200

# VoxPro Manager routing
[[redirects]]
  from = "/voxpro-manager"
  to = "/templates/voxpro-manager.html"
  status = 200

# Static assets
[[redirects]]
  from = "/assets/*"
  to = "/assets/:splat"
  status = 200

# Root redirect to VoxPro Manager
[[redirects]]
  from = "/"
  to = "/voxpro-manager"
  status = 302

# Catch-all redirect (should be last)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Headers for CORS and security
[[headers]]
  for = "/api/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Headers = "Content-Type, Authorization"
    Access-Control-Allow-Methods = "GET, POST, PUT, DELETE, OPTIONS"

[[headers]]
  for = "/.netlify/functions/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Headers = "Content-Type, Authorization"
    Access-Control-Allow-Methods = "GET, POST, PUT, DELETE, OPTIONS"
